const allRoles = {
  student: [
    'getProfile',
    'updateProfile',
    'getLearningPaths',
    'getModules',
    'getAssessments',
    'submitAssessment',
    'getProjects',
    'submitProject',
    'joinMentorSession',
    'getCertificates',
    'getJobs',
    'applyJob',
    'getInternships',
    'applyInternship',
    'getMentors',
    'requestMentorship',
    'joinCommunity',
    'createCommunityPost',
    'rateContent',
    'getCompetitions',
    'joinCompetition',
    'getSkillReports',
    'getRecommendations',
  ],
  mentor: [
    'getProfile',
    'updateProfile',
    'getMentorships',
    'createMentorSession',
    'updateMentorSession',
    'cancelMentorSession',
    'reviewProject',
    'reviewAssessment',
    'createContent',
    'editContent',
    'getStudents',
    'getSkillReports',
    'createRecommendation',
    'getMentorPayments',
  ],
  admin: [
    'getUsers',
    'manageUsers',
    'getLearningPaths',
    'createLearningPath',
    'updateLearningPath',
    'deleteLearningPath',
    'getModules',
    'createModule',
    'updateModule',
    'deleteModule',
    'getPartners',
    'createPartner',
    'updatePartner',
    'deletePartner',
    'getEmployers',
    'createEmployer',
    'updateEmployer',
    'deleteEmployer',
    'getAnalytics',
    'getReports',
    'manageSystem',
    'managePayments',
    'manageCertifications',
    'manageContent',
  ],
  institution: [
    'getProfile',
    'updateProfile',
    'getStudents',
    'getAnalytics',
    'getReports',
    'getFaculty',
    'createFaculty',
    'updateFaculty',
    'deleteFaculty',
    'getFacilitySchedule',
    'updateFacilitySchedule',
    'getPartnerMetrics',
  ],
  employer: [
    'getProfile',
    'updateProfile',
    'postJob',
    'updateJob',
    'deleteJob',
    'postInternship',
    'updateInternship',
    'deleteInternship',
    'reviewApplications',
    'scheduleInterview',
    'getReports',
    'getSuggestedCandidates',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
